### ISSUE TITLE
Why is "bzr" installed by 0-sudo-init.sh?

### ISSUE THREAD

**Issue by herb-kuta-lge** [shr-project/test-oe-build-time#1]
`bzr` doesn't appear in the list of [Yocto prerequisites for Ubuntu](https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#ubuntu-packages). Is it actually necessary for the test?

**Comment by shr-project** [comment]
bzr is needed for bitbake's bzr:// fetcher to work:
```
meta/conf/bitbake.conf:# Used by bzr fetcher
meta/conf/bitbake.conf:HOSTTOOLS_NONFATAL += "bzr"
```

There aren't many recipes using bzr fetcher, I know about 2 in LuneOS for qtubuntu-camera (neither of them is included in this test), but having bzr installed for OE builds in general is good for sanity (the error from the fetcher IIRC isn't very clear that you're expected to install native bzr yourself - and also to delete hosttools directory to regenerate it).

**Comment by herb-kuta-lge** [comment]
> having bzr installed for OE builds in general is good for sanity

Then please submit a change to add it to lists the Yocto MegaManual (there are two lists of prerequisites in the document)..

**Comment by shr-project** [comment]
The MegaManual lists only essential dependencies, at least in:
https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#required-packages-for-the-build-host
https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#brief-build-system-packages

bzr isn't essential (as not checked by HOSTTOOLS variable and sanity.bbclass), it's still useful to have, but shouldn't be part of neither these 2 lists. You can add it in separate section in the manual, but getting that change merged might take a while now - but there is now separate ML for documentation discussion since 3 weeks ago:
https://lists.yoctoproject.org/g/docs

**Comment by herb-kuta-lge** [comment]
> bzr isn't essential (as not checked by HOSTTOOLS variable and sanity.bbclass), it's still useful to have, but shouldn't be part of neither these 2 lists.

> the error from the fetcher IIRC isn't very clear that you're expected to install native bzr yourself - and also to delete hosttools directory to regenerate it

Then perhaps what should be changed is the fetcher error message?

**Comment by shr-project** [comment]
Feel free to change it in bitbake (and re-test if the message is still confusing), just keep in mind that people can set it to their own bzr somewhere with FETCHCMD_bzr, so it's not just test for bzr in PATH (or in HOSTTOOLS):
```
lib/bb/fetch2/bzr.py:        basecmd = d.getVar("FETCHCMD_bzr") or "/usr/bin/env bzr"
```
